language: php

dist: bionic

php:
  - 8.2

services:
  - mysql
  - redis

before_script:
  - cp .env.example .env
  - mysql -e "CREATE DATABASE example_app"
  - composer self-update
  - composer install --no-interaction --prefer-source
  - ./vendor/bin/sail php artisan key:generate
  - ./vendor/bin/sail php artisan migrate

script:
  - vendor/bin/phpunit
